### PR TITLE
[Feature] iOS 14 & Xcode 12 compatibility

### PR DESCRIPTION
**Pull request by xavierjurado**
This PR backports all the issues described in https://github.com/google/EarlGrey/issues/1357 to EarlGrey v1. Where possible I've cherry-picked the original commit:

* XCTestCase::recordIssue support: https://github.com/google/EarlGrey/pull/1377
* UITouch private API changes (based on @steipe approach published in https://github.com/google/EarlGrey/issues/1357)
* Disable caret blink animation: https://github.com/google/EarlGrey/pull/1404/

Additionally I've also backported/fixed other small issues:

* Duplicate TextField id's: https://github.com/google/EarlGrey/pull/1391/ 
* Remove duplicated/invalid file references from Build Phase
* Explicitly remove support for arm64 simulator (Apple Silicon) (not supported by ochamcrest)
* Configure indentation to match existing guidelines
* Fix deprecated developmentRegion
* Fix weird documentation error due to an escaped character

---

Please note Google no longer maintains EarlGrey v1 as stated in the official repository. See https://github.com/google/EarlGrey/pull/1431 for more information.

### CODE REVIEW

**Comment by wellavelino** [comment]
@xavierjurado do you by any chance if they will backport this PR in the original repo?

**Comment by xavierjurado** [comment]
@wellavelino no, they have stated in the linked PR that they no longer maintain EarlGrey v1.

**Comment by wellavelino** [comment]
=/ 
ye i saw that, i was hopping they would have support for iOS 14 on EarlGrey v2

**Comment by xavierjurado** [comment]
The do support iOS 14 on EarlGrey v2 afaik, it's only the v1 branch that is no longer maintained 😮

**Comment by er-aman-gupta** [comment]
Hi @xavierjurado , wanted to know how can i use this in my project. currently i'm using earlgrey as a pod from the master repo. how do i start using urs?

**Comment by xavierjurado** [comment]
@er-aman-gupta for now something like this should do the trick:

```ruby
pod 'EarlGrey', :podspec => 'https://raw.githubusercontent.com/AdevintaSpain/EarlGrey/master/EarlGrey.podspec.json'
``` 

We may release the fork to the public under a different name in the near future, which should make things even easier.

**Comment by er-aman-gupta** [comment]
This worked. Thanks a lot @xavierjurado

**Pull request merged**
